services:
  tiago_base:
    extends:
      file: .compose_templates.yml
      service: .tiago_sim
    command: >
      ros2 launch rwu_tiago_bringup sim_robocup_2023.launch.py
      x:=-3.0 y:=-1.0 yaw:=1.6 is_public_sim:=True navigation:=True slam:=False map_path:=/maps/testmap_backup.yaml

  rviz:
    extends:
      file: .compose_templates.yml
      service: .tiago_sim
    command: >
      bash -c "sleep 15 && rviz2 -d /config/moveit2.rviz"
    depends_on:
      - tiago_base
   
  tiago_workspace:
    image: fbe-dockerreg.rwu.de/prj-iki-ros2/robots/tiago/tiago_base:sim
    extends:
      file: .compose_templates.yml
      service: .workspace_gui
    
    command: >
      bash -lc "
        echo '=== Building workspace ===';
        cd /root/ros2_ws;

        rm -rf build/moveit_wrapper_interfaces install/moveit_wrapper_interfaces log || true;

        colcon build --symlink-install --packages-select moveit_wrapper_interfaces clean_the_table || {
          echo '❌ colcon failed (package missing or symlink issue). Keeping container alive...';
          tail -f /dev/null;
        };

        source /root/ros2_ws/install/setup.bash;

        sleep 15;

        until ros2 topic list | grep -q '/joint_states'; do
          echo 'Waiting for /joint_states...';
          sleep 3;
        done;

        cd /root/ros2_ws/src/25ws_sk-246767/models || { echo 'models folder not found'; tail -f /dev/null; }
        python3 spawn_objects_clean_table.py &

        ros2 run clean_the_table start_inspection --ros-args -p use_sim_time:=true

        tail -f /dev/null
      "
    depends_on:
      - tiago_base
      - moveit_wrapper
      - apriltag_detection
      
  moveit_wrapper:
    extends:
      file: ../submodules/moveit_wrapper_stud/docker/compose-gpu.yaml
      service: moveit_wrapper
    depends_on:
      - tiago_base
      
  apriltag_detection:
    extends:
      file: ros2-apriltag.yml
      service: apriltag_detection
    depends_on:
      - tiago_base