services:
  apriltag_detection:
    container_name: ros2_apriltag_detection
    image: fbe-dockerreg.rwu.de/prj-iki-ros2/perception/apriltag:humble
    environment:
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    network_mode: host
    restart: 'unless-stopped'
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../submodules/ros-2-apriltags/configs:/cfg:ro
    command: 
    - bash
    - -c
    - |
          ros2 run apriltag_ros apriltag_node \
            --ros-args \
            -r image_rect:=/head_front_camera/rgb/image_raw \
            -r camera_info:=/head_front_camera/rgb/camera_info \
            --params-file /cfg/tags_36h11.yaml

